package com.abak.entity;
// Generated 3 Jun, 2019 12:29:30 PM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Panel generated by hbm2java
 */
@Entity
@Table(name = "panel", catalog = "abak")
public class Panel implements java.io.Serializable,Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6388190023939279972L;
	private Integer panelId;
	private Project project;
	private String panelName;
	private Integer hight;
	private Integer width;
	private Integer depth;
	private Integer quntity;
	private Double unitRate;
	private Double totalEbom;
	private Double additionalComponentTotal;
	private Integer laborPersentage;
	private Double laborCost;
	private Integer overHeadPersentage;
	private Double overHeadCost;
	private Double factoryCost;
	private Integer marginPersentage;
	private Double marginCost;
	private Double transportCost;
	private Double woodenCratePakagingCost;
	private Double miscellaneousCost;
	private Double miscellaneousCostPercentage;
	private Double transportPercentage;
	private Double woodenCratePakagingCostPercentage;
	private Double netTotal;
	private Double grandRounedTotal;
	private Double negotiatedPrice;
	private Double ebonPrize;
	private List<PanelAdditionalComponent> panelAdditionalComponents = new ArrayList<PanelAdditionalComponent>(0);
	private List<PanelDetails> panelDetailses = new ArrayList<PanelDetails>(0);
	private List<PanelSpecification> panelSpecifications = new ArrayList<>(0);

	 
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "panel_id", unique = true, nullable = false)
	public Integer getPanelId() {
		return this.panelId;
	}

	public void setPanelId(Integer panelId) {
		this.panelId = panelId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "panel_name", length = 100)
	public String getPanelName() {
		return this.panelName;
	}

	public void setPanelName(String panelName) {
		this.panelName = panelName;
	}

	@Column(name = "hight")
	public Integer getHight() {
		return this.hight;
	}

	public void setHight(Integer hight) {
		this.hight = hight;
	}

	@Column(name = "width")
	public Integer getWidth() {
		return this.width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	@Column(name = "DEPTH")
	public Integer getDepth() {
		return this.depth;
	}

	public void setDepth(Integer depth) {
		this.depth = depth;
	}

	@Column(name = "quntity")
	public Integer getQuntity() {
		return this.quntity;
	}

	public void setQuntity(Integer quntity) {
		this.quntity = quntity;
	}

	@Column(name = "unit_rate", precision = 22, scale = 0)
	public Double getUnitRate() {
		return this.unitRate;
	}

	public void setUnitRate(Double unitRate) {
		this.unitRate = unitRate;
	}

	@Column(name = "total_EBOM", precision = 22, scale = 0)
	public Double getTotalEbom() {
		return this.totalEbom;
	}

	public void setTotalEbom(Double totalEbom) {
		this.totalEbom = totalEbom;
	}

	@Column(name = "additional_component_total", precision = 22, scale = 0)
	public Double getAdditionalComponentTotal() {
		return this.additionalComponentTotal;
	}

	public void setAdditionalComponentTotal(Double additionalComponentTotal) {
		this.additionalComponentTotal = additionalComponentTotal;
	}

	@Column(name = "labor_persentage")
	public Integer getLaborPersentage() {
		return this.laborPersentage;
	}

	public void setLaborPersentage(Integer laborPersentage) {
		this.laborPersentage = laborPersentage;
	}

	@Column(name = "labor_cost", precision = 22, scale = 0)
	public Double getLaborCost() {
		return this.laborCost;
	}

	public void setLaborCost(Double laborCost) {
		this.laborCost = laborCost;
	}

	@Column(name = "overHead_persentage")
	public Integer getOverHeadPersentage() {
		return this.overHeadPersentage;
	}

	public void setOverHeadPersentage(Integer overHeadPersentage) {
		this.overHeadPersentage = overHeadPersentage;
	}

	@Column(name = "overHead_cost", precision = 22, scale = 0)
	public Double getOverHeadCost() {
		return this.overHeadCost;
	}

	public void setOverHeadCost(Double overHeadCost) {
		this.overHeadCost = overHeadCost;
	}

	@Column(name = "factory_cost", precision = 22, scale = 0)
	public Double getFactoryCost() {
		return this.factoryCost;
	}

	public void setFactoryCost(Double factoryCost) {
		this.factoryCost = factoryCost;
	}

	@Column(name = "margin_persentage")
	public Integer getMarginPersentage() {
		return this.marginPersentage;
	}

	public void setMarginPersentage(Integer marginPersentage) {
		this.marginPersentage = marginPersentage;
	}

	@Column(name = "margin_cost", precision = 22, scale = 0)
	public Double getMarginCost() {
		return this.marginCost;
	}

	public void setMarginCost(Double marginCost) {
		this.marginCost = marginCost;
	}

	@Column(name = "transport_cost", precision = 22, scale = 0)
	public Double getTransportCost() {
		return this.transportCost;
	}

	public void setTransportCost(Double transportCost) {
		this.transportCost = transportCost;
	}

	@Column(name = "wooden_crate_pakaging_cost", precision = 22, scale = 0)
	public Double getWoodenCratePakagingCost() {
		return this.woodenCratePakagingCost;
	}

	public void setWoodenCratePakagingCost(Double woodenCratePakagingCost) {
		this.woodenCratePakagingCost = woodenCratePakagingCost;
	}

	@Column(name = "net_total", precision = 22, scale = 0)
	public Double getNetTotal() {
		return this.netTotal;
	}

	public void setNetTotal(Double netTotal) {
		this.netTotal = netTotal;
	}

	@Column(name = "grand_rouned_total", precision = 22, scale = 0)
	public Double getGrandRounedTotal() {
		return this.grandRounedTotal;
	}

	public void setGrandRounedTotal(Double grandRounedTotal) {
		this.grandRounedTotal = grandRounedTotal;
	}

	@Column(name = "negotiated_price", precision = 22, scale = 0)
	public Double getNegotiatedPrice() {
		return this.negotiatedPrice;
	}

	public void setNegotiatedPrice(Double negotiatedPrice) {
		this.negotiatedPrice = negotiatedPrice;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "panel", cascade = { CascadeType.ALL,CascadeType.PERSIST,CascadeType.MERGE })
	public List<PanelAdditionalComponent> getPanelAdditionalComponents() {
		return this.panelAdditionalComponents;
	}

	public void setPanelAdditionalComponents(List<PanelAdditionalComponent> panelAdditionalComponents) {
		this.panelAdditionalComponents = panelAdditionalComponents;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "panel", cascade = { CascadeType.ALL,CascadeType.PERSIST,CascadeType.MERGE })
	public List<PanelDetails> getPanelDetailses() {
		return this.panelDetailses;
	}

	public void setPanelDetailses(List<PanelDetails> panelDetailses) {
		this.panelDetailses = panelDetailses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "panel" , cascade = { CascadeType.ALL,CascadeType.PERSIST,CascadeType.MERGE })
	public List<PanelSpecification> getPanelSpecifications() {
		return this.panelSpecifications;
	}

	public void setPanelSpecifications(List<PanelSpecification> panelSpecifications) {
		this.panelSpecifications = panelSpecifications;
	}

	@Column(name = "miscellaneous_cost", precision = 22, scale = 0)
	public Double getMiscellaneousCost() {
		return miscellaneousCost;
	}

	public void setMiscellaneousCost(Double miscellaneousCost) {
		this.miscellaneousCost = miscellaneousCost;
	}

	@Column(name = "miscellaneous_cost_percentage", precision = 22, scale = 0)
	public Double getMiscellaneousCostPercentage() {
		return miscellaneousCostPercentage;
	}

	public void setMiscellaneousCostPercentage(Double miscellaneousCostPercentage) {
		this.miscellaneousCostPercentage = miscellaneousCostPercentage;
	}

	@Column(name = "transport_percentage", precision = 22, scale = 0)
	public Double getTransportPercentage() {
		return transportPercentage;
	}

	public void setTransportPercentage(Double transportPercentage) {
		this.transportPercentage = transportPercentage;
	}

	@Column(name = "wooden_crate_pakaging_cost_percentage", precision = 22, scale = 0)
	public Double getWoodenCratePakagingCostPercentage() {
		return woodenCratePakagingCostPercentage;
	}

	public void setWoodenCratePakagingCostPercentage(Double woodenCratePakagingCostPercentage) {
		this.woodenCratePakagingCostPercentage = woodenCratePakagingCostPercentage;
	}

	@Column(name = "ebon_prize", precision = 22, scale = 0)
	public Double getEbonPrize() {
		return ebonPrize;
	}

	public void setEbonPrize(Double ebonPrize) {
		this.ebonPrize = ebonPrize;
	}

	@Override
	public Object clone()throws CloneNotSupportedException{
		return super.clone();
	}


}
