package com.abak.entity;
// Generated 3 Jun, 2019 12:29:30 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PanelAdditionalComponent generated by hbm2java
 */
@Entity
@Table(name = "panel_additional_component", catalog = "abak")
public class PanelAdditionalComponent implements java.io.Serializable,Cloneable {

	private Integer panelAdditionalComponentId;
	private Panel panel;
	private int projectId;
	private String componentDescription;
	private Integer quntity;
	private Double rate;
	private Double cost;

	public PanelAdditionalComponent() {
	}

	public PanelAdditionalComponent(Panel panel, int projectId) {
		this.panel = panel;
		this.projectId = projectId;
	}

	public PanelAdditionalComponent(Panel panel, int projectId, String componentDescription, Integer quntity,
			Double rate, Double cost) {
		this.panel = panel;
		this.projectId = projectId;
		this.componentDescription = componentDescription;
		this.quntity = quntity;
		this.rate = rate;
		this.cost = cost;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Panel_additional_component_id", unique = true, nullable = false)
	public Integer getPanelAdditionalComponentId() {
		return this.panelAdditionalComponentId;
	}

	public void setPanelAdditionalComponentId(Integer panelAdditionalComponentId) {
		this.panelAdditionalComponentId = panelAdditionalComponentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "panel_id", nullable = false)
	public Panel getPanel() {
		return this.panel;
	}

	public void setPanel(Panel panel) {
		this.panel = panel;
	}

	@Column(name = "project_id")
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "component_description", length = 100)
	public String getComponentDescription() {
		return this.componentDescription;
	}

	public void setComponentDescription(String componentDescription) {
		this.componentDescription = componentDescription;
	}

	@Column(name = "quntity")
	public Integer getQuntity() {
		return this.quntity;
	}

	public void setQuntity(Integer quntity) {
		this.quntity = quntity;
	}

	@Column(name = "rate", precision = 22, scale = 0)
	public Double getRate() {
		return this.rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	@Column(name = "cost", precision = 22, scale = 0)
	public Double getCost() {
		return this.cost;
	}

	public void setCost(Double cost) {
		this.cost = cost;
	}

	public Object clone()throws CloneNotSupportedException{
		return super.clone();
	}

}
