package com.abak.entity;
// Generated 20 Jul, 2019 10:06:34 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Quotation generated by hbm2java
 */
@Entity
@Table(name = "quotation")
public class Quotation implements java.io.Serializable {

	private Integer id;
	private int projectId;
	private String contruction;
	private String system;
	private String painting;
	private String busbar;
	private String earthing;
	private String wiring;
	private String delivery;
	private Integer clientId;
	private String clientEmail;

	public Quotation() {
	}

	public Quotation(int projectId) {
		this.projectId = projectId;
	}

	public Quotation(int projectId, String contruction, String system, String painting, String busbar, String earthing,
			String wiring, String delivery, Integer clientId, String clientEmail) {
		this.projectId = projectId;
		this.contruction = contruction;
		this.system = system;
		this.painting = painting;
		this.busbar = busbar;
		this.earthing = earthing;
		this.wiring = wiring;
		this.delivery = delivery;
		this.clientId = clientId;
		this.clientEmail = clientEmail;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "project_id", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "contruction", length = 200)
	public String getContruction() {
		return this.contruction;
	}

	public void setContruction(String contruction) {
		this.contruction = contruction;
	}

	@Column(name = "system", length = 200)
	public String getSystem() {
		return this.system;
	}

	public void setSystem(String system) {
		this.system = system;
	}

	@Column(name = "painting", length = 200)
	public String getPainting() {
		return this.painting;
	}

	public void setPainting(String painting) {
		this.painting = painting;
	}

	@Column(name = "busbar", length = 200)
	public String getBusbar() {
		return this.busbar;
	}

	public void setBusbar(String busbar) {
		this.busbar = busbar;
	}

	@Column(name = "earthing", length = 200)
	public String getEarthing() {
		return this.earthing;
	}

	public void setEarthing(String earthing) {
		this.earthing = earthing;
	}

	@Column(name = "wiring", length = 200)
	public String getWiring() {
		return this.wiring;
	}

	public void setWiring(String wiring) {
		this.wiring = wiring;
	}

	@Column(name = "delivery", length = 200)
	public String getDelivery() {
		return this.delivery;
	}

	public void setDelivery(String delivery) {
		this.delivery = delivery;
	}

	@Column(name = "client_Id")
	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	@Column(name = "client_email", length = 200)
	public String getClientEmail() {
		return this.clientEmail;
	}

	public void setClientEmail(String clientEmail) {
		this.clientEmail = clientEmail;
	}

}
